package com.epam.lab.web.soap;

import com.epam.lab.model.Book;
import com.epam.lab.web.LibraryService;
import com.epam.lab.web.fault.ServiceException;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-24T22:44:48.319+03:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://web.soap.lab.epam.com/", name = "LibrarySOAPService")
@XmlSeeAlso({ObjectFactory.class})
public interface LibrarySOAPService extends LibraryService{

    @WebMethod
    @RequestWrapper(localName = "getBook", targetNamespace = "http://web.soap.lab.epam.com/", className = "GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "GetBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Book getBook(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "exchangeBook", targetNamespace = "http://web.soap.lab.epam.com/", className = "ExchangeBook")
    @ResponseWrapper(localName = "exchangeBookResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "ExchangeBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Book exchangeBook(
        @WebParam(name = "arg0", targetNamespace = "")
                Book arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "turnBackBook", targetNamespace = "http://web.soap.lab.epam.com/", className = "TurnBackBook")
    @ResponseWrapper(localName = "turnBackBookResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "TurnBackBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean turnBackBook(
        @WebParam(name = "arg0", targetNamespace = "")
                Book arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://web.soap.lab.epam.com/", className = "GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "GetAllBooksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Book> getAllBooks();

    @WebMethod
    @RequestWrapper(localName = "getAuthorBooks", targetNamespace = "http://web.soap.lab.epam.com/", className = "GetAuthorBooks")
    @ResponseWrapper(localName = "getAuthorBooksResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "GetAuthorBooksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Book> getAuthorBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws ServiceException;
}
