package com.epam.lab.soap.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-22T15:21:09.724+03:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://web.soap.lab.epam.com/", name = "LibraryService")
@XmlSeeAlso({ObjectFactory.class})
public interface LibraryService {

    @WebMethod
    @RequestWrapper(localName = "getBook", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.GetBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.epam.lab.soap.web.Book getBook(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "exchangeBook", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.ExchangeBook")
    @ResponseWrapper(localName = "exchangeBookResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.ExchangeBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.epam.lab.soap.web.Book exchangeBook(
        @WebParam(name = "arg0", targetNamespace = "")
        com.epam.lab.soap.web.Book arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws ServiceException;

    @WebMethod
    @RequestWrapper(localName = "turnBackBook", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.TurnBackBook")
    @ResponseWrapper(localName = "turnBackBookResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.TurnBackBookResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean turnBackBook(
        @WebParam(name = "arg0", targetNamespace = "")
        com.epam.lab.soap.web.Book arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.GetAllBooksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.epam.lab.soap.web.Book> getAllBooks();

    @WebMethod
    @RequestWrapper(localName = "getAuthorBooks", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.GetAuthorBooks")
    @ResponseWrapper(localName = "getAuthorBooksResponse", targetNamespace = "http://web.soap.lab.epam.com/", className = "com.epam.lab.soap.web.GetAuthorBooksResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.epam.lab.soap.web.Book> getAuthorBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws ServiceException;
}
