package com.epam.lab.soap.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-22T15:21:09.742+03:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "LibraryServiceImplService", 
                  wsdlLocation = "file:/D:/Tsyhanko/workspace/MykhailoTsyhankoSOAPClient/src/main/resources/service.wsdl",
                  targetNamespace = "http://web.soap.lab.epam.com/") 
public class LibraryServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.soap.lab.epam.com/", "LibraryServiceImplService");
    public final static QName LibraryServiceImplPort = new QName("http://web.soap.lab.epam.com/", "LibraryServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Tsyhanko/workspace/MykhailoTsyhankoSOAPClient/src/main/resources/service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LibraryServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Tsyhanko/workspace/MykhailoTsyhankoSOAPClient/src/main/resources/service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LibraryServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LibraryServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LibraryServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LibraryServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LibraryServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LibraryService
     */
    @WebEndpoint(name = "LibraryServiceImplPort")
    public LibraryService getLibraryServiceImplPort() {
        return super.getPort(LibraryServiceImplPort, LibraryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibraryService
     */
    @WebEndpoint(name = "LibraryServiceImplPort")
    public LibraryService getLibraryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(LibraryServiceImplPort, LibraryService.class, features);
    }

}
