
package com.epam.lab.soap.web;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-22T15:21:09.697+03:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "LibraryFault", targetNamespace = "http://web.soap.lab.epam.com/")
public class ServiceException extends Exception {
    
    private LibraryFault libraryFault;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, LibraryFault libraryFault) {
        super(message);
        this.libraryFault = libraryFault;
    }

    public ServiceException(String message, LibraryFault libraryFault, Throwable cause) {
        super(message, cause);
        this.libraryFault = libraryFault;
    }

    public LibraryFault getFaultInfo() {
        return this.libraryFault;
    }
}
